import Head from 'next/head'
import About from './Components/About'
import Contact from './Components/Contact'
import Experience from './Components/Experience'
import Header from './Components/Header'
import Hero from './Components/Hero'
import Projects from './Components/Projects'
import Skills from './Components/Skills'

export default function Home() {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0'>
      <Head>
        <title>Samy's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section id='hero' className='snap-start'>
        <Hero />
      </section>

      <section id='about' className='snap-start'>
        <About />
      </section>

      <section id='experience' className='snap-center'>
        <Experience/>
      </section>

      <section id='skills' className='snap-start'>
        <Skills/>
      </section>

      <section id='projects' className='snap-start'>
        <Projects/>
      </section>
      
      <section id='contact' className='snap-start'>
        <Contact/>
      </section> 
    </div>
  )
}
